In [604]:
import pandas as pd

In [605]:
data=pd.read_csv('churn.csv') #importar os dados
print(data.head())

  State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Mins  Day Calls  Day Charge   ...    Eve Calls  \
0             25     265.1        110       45.07   ...           99   
1             26     161.6        123       27.47   ...          103   
2              0     243.4        114       41.38   ...          110   
3              0     299.4         71       50.90   ...           88   
4              0     166.7        113       28.34   ...          122   

   Eve Charge  Night Mins  Night Calls  Night Charge  Intl Mins  Intl Calls  \
0       16.78       244.7           91         11.01       10.0    

In [606]:
data.dtypes

State              object
Account Length      int64
Area Code           int64
Phone              object
Int'l Plan         object
VMail Plan         object
VMail Message       int64
Day Mins          float64
Day Calls           int64
Day Charge        float64
Eve Mins          float64
Eve Calls           int64
Eve Charge        float64
Night Mins        float64
Night Calls         int64
Night Charge      float64
Intl Mins         float64
Intl Calls          int64
Intl Charge       float64
CustServ Calls      int64
Churn?             object
dtype: object

In [607]:
obj_data = data.select_dtypes(include=['object', 'int64']).copy()
obj_data.head()

State  Account Length  Area Code     Phone Int'l Plan VMail Plan  \
0    KS             128        415  382-4657         no        yes   
1    OH             107        415  371-7191         no        yes   
2    NJ             137        415  358-1921         no         no   
3    OH              84        408  375-9999        yes         no   
4    OK              75        415  330-6626        yes         no   

   VMail Message  Day Calls  Eve Calls  Night Calls  Intl Calls  \
0             25        110         99           91           3   
1             26        123        103          103           3   
2              0        114        110          104           5   
3              0         71         88           89           7   
4              0        113        122          121           3   

   CustServ Calls  Churn?  
0               1  False.  
1               1  False.  
2               0  False.  
3               2  False.  
4               3  False.

In [608]:
obj_data[obj_data.isnull().any(axis=1)]

Empty DataFrame
Columns: [State, Account Length, Area Code, Phone, Int'l Plan, VMail Plan, VMail Message, Day Calls, Eve Calls, Night Calls, Intl Calls, CustServ Calls, Churn?]
Index: []

In [609]:
obj_data = obj_data.drop(['Phone'], axis=1)
#obj_data = obj_data.drop(['State'], axis=1)
obj_data = obj_data.drop(['Area Code'], axis=1)


In [610]:
#pd.get_dummies(obj_data, columns=["State"]).head()
#pd.get_dummies(obj_data, columns=["Int'l Plan"]).head()
#pd.get_dummies(obj_data, columns=["VMail Plan"]).head()

In [611]:
#obj_data = pd.get_dummies(obj_data, columns=["State", "Int'l Plan", "VMail Plan"], prefix=["State", "Int'l Plan", "VMail Plan"])
obj_data = pd.get_dummies(obj_data, columns=["State"], prefix=["State"])
obj_data["Int'l Plan"] = np.where(obj_data["Int'l Plan"] == 'yes',1,0)
obj_data["VMail Plan"] = np.where(obj_data["VMail Plan"] == 'yes',1,0)

In [612]:
obj_data

Account Length  Int'l Plan  VMail Plan  VMail Message  Day Calls  \
0                128           0           1             25        110   
1                107           0           1             26        123   
2                137           0           0              0        114   
3                 84           1           0              0         71   
4                 75           1           0              0        113   
5                118           1           0              0         98   
6                121           0           1             24         88   
7                147           1           0              0         79   
8                117           0           0              0         97   
9                141           1           1             37         84   
10                65           0           0              0        137   
11                74           0           0              0        127   
12               168           0           0              0         96   
13                95           0           0              0         88   
14                62           0           0              0         70   
15               161           0           0              0         67   
16                85           0           1             27        139   
17                93           0           0              0        114   
18                76           0           1             33         66   
19                73           0           0              0         90   
20               147           0           0              0        117   
21                77           0           0              0         89   
22               130           0           0              0        112   
23               111           0           0              0        103   
24               132           0           0              0         86   
25               174           0           0              0         76   
26                57           0           1             39        115   
27                54           0           0              0         73   
28                20           0           0              0        109   
29                49           0           0              0        117   
...              ...         ...         ...            ...        ...   
3303             114           0           1             26         88   
3304              71           1           0              0        114   
3305              58           0           1             22        127   
3306             106           0           1             29        131   
3307             172           0           0              0        109   
3308              45           0           0              0         87   
3309             100           1           0              0        112   
3310              94           0           0              0         91   
3311             128           0           0              0         94   
3312             181           0           0              0        130   
3313             127           0           0              0        128   
3314              89           0           0              0         81   
3315             149           0           1             18        106   
3316             103           0           1             29        111   
3317             163           1           0              0         90   
3318              52           0           0              0        131   
3319              89           0           0              0         99   
3320             122           1           0              0        101   
3321              60           0           0              0        118   
3322              62           0           0              0        105   
3323             117           0           0              0        126   
3324             159           0           0              0        114   
3325      

In [613]:
from sklearn.cluster import KMeans
import numpy as np

In [614]:
data_cluster = obj_data.drop(['Churn?'], axis=1)
kmeans = KMeans(n_clusters=2).fit(data_cluster)

In [615]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [616]:
x = data_cluster
y = obj_data['Churn?']

In [617]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.40)

In [618]:
data_tree = DecisionTreeClassifier()

In [619]:
data_tree.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [620]:
churn_predictions = data_tree.predict(x_test)

In [621]:
from sklearn.metrics import classification_report,confusion_matrix

In [622]:
print(classification_report(y_test,churn_predictions))

             precision    recall  f1-score   support

     False.       0.90      0.89      0.89      1147
      True.       0.35      0.36      0.36       187

avg / total       0.82      0.82      0.82      1334



In [623]:
from sklearn.metrics import accuracy_score

In [624]:
print(confusion_matrix(y_test,churn_predictions))

[[1025  122]
 [ 120   67]]


In [625]:
print(accuracy_score(y_test,churn_predictions))

0.8185907046476761


In [626]:
data_tree_en = DecisionTreeClassifier(criterion='entropy',min_samples_split=200)
data_tree_en.fit(x_train,y_train)
churn_predictions_en = data_tree_en.predict(x_test)

In [627]:
print(classification_report(y_test,churn_predictions_en))
print(confusion_matrix(y_test,churn_predictions_en))
print(accuracy_score(y_test,churn_predictions_en))

             precision    recall  f1-score   support

     False.       0.89      0.95      0.92      1147
      True.       0.49      0.30      0.38       187

avg / total       0.84      0.86      0.84      1334

[[1087   60]
 [ 130   57]]
0.8575712143928036


In [628]:
param_grid = [
  {'criterion': ['gini', 'entropy'], 'min_samples_split': [2,4,6,8]}
 ]

from sklearn.model_selection import GridSearchCV
simple_tree = DecisionTreeClassifier()
grid_model = GridSearchCV(simple_tree, param_grid)

grid_model.fit(x_train,y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'criterion': ['gini', 'entropy'], 'min_samples_split': [2, 4, 6, 8]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [629]:
churn_predictions_all = grid_model.predict(x_test)

In [630]:
print(classification_report(y_test,churn_predictions_all))
print(confusion_matrix(y_test,churn_predictions_all))
print(accuracy_score(y_test,churn_predictions_all))

             precision    recall  f1-score   support

     False.       0.89      0.91      0.90      1147
      True.       0.37      0.32      0.34       187

avg / total       0.82      0.83      0.82      1334

[[1046  101]
 [ 127   60]]
0.8290854572713643


In [631]:
print(accuracy_score(y_test,churn_predictions))
print(accuracy_score(y_test,churn_predictions_en))
print(accuracy_score(y_test,churn_predictions_all))

0.8185907046476761
0.8575712143928036
0.8290854572713643
